### ISSUE TITLE
the version

### ISSUE THREAD

**Issue by Yang507** [da03/Attention-OCR#21]
I use the keras version 1.1.1 and tensorflow 0.10 is not fit to your new updated program, there is a problem:`raise TypeError("List of Tensors when single Tensor expected") TypeError: List of Tensors when single Tensor expected`.

**Comment by da03** [comment]
Thanks for the feedback! Do you have a detailed error message? And actually I was testing on the latest tensorflow (0.11).

**Comment by Yang507** [comment]
the detail error:
    
    Traceback (most recent call last):
     File "src/launcher.py", line 136, in <module>
      main(sys.argv[1:], exp_config.ExpConfig)
     File "src/launcher.py", line 132, in main
      session = sess)
     File "/home/yanghang/Attention-OCR/src/model/model.py", line 167, in __init__
      self.keras_updates.append(tf.assign(old_value, new_value))
      File "~/anaconda2/lib/python2.7/site-packages/tensorflow/python       /ops/gen_state_ops.py", line 45, in assign
    use_locking=use_locking, name=name)
     File "~/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 454, in apply_op
    as_ref=input_arg.is_ref)
     File "~/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 621, in convert_to_tensor
      ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
     File "~/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 180, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
    File "~/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/constant_op.py", line 163, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape))
    File "~/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 353, in make_tensor_proto
    _AssertCompatible(values, dtype)
    File "~/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py", line 287, in _AssertCompatible
    raise TypeError("List of Tensors when single Tensor expected")
    TypeError: List of Tensors when single Tensor expected.
I hope this can help you!

**Comment by Yang507** [comment]
I doubt whether is tensorflow's version problem, i don't want to upgrade tensorflow version to 11 now.

**Comment by Yang507** [comment]
I used the keras version 1.0.4 and tensorflow 0.10, I run the old code(before you updated the code) and restart to train my data , but encountered a problem:
    `Traceback (most recent call last):
  File "src/launcher.py", line 129, in <module>
    main(sys.argv[1:], exp_config.ExpConfig)
  File "src/launcher.py", line 126, in main
    model.launch()
  File "~/anaconda2/Attention-OCR-master/src/model/model.py", line 279, in launch
    _, step_loss, step_logits, _ = self.step(encoder_masks, img_data, zero_paddings, decoder_inputs, target_weights, bucket_id, self.forward_only)
UnboundLocalError: local variable 'img_data' referenced before assignment`
