### ISSUE TITLE
AttributeError: 'InputLayer' object has no attribute 'set_input'

### ISSUE THREAD

**Issue by webluoye** [da03/Attention-OCR#25]
python -V
Python 2.7.10

python src/launcher.py --phase=train --data-path=sample/sample.txt --data-base-dir=sample --log-path=log.txt --no-load-model
Using TensorFlow backend.
2017-01-09 11:52:13,224 root  INFO     loading data
2017-01-09 11:52:13,225 root  INFO     data_path: sample/sample.txt
2017-01-09 11:52:13,225 root  INFO     phase: train
2017-01-09 11:52:13,225 root  INFO     batch_size: 64
2017-01-09 11:52:13,225 root  INFO     num_epoch: 1000
2017-01-09 11:52:13,225 root  INFO     steps_per_checkpoint 500
2017-01-09 11:52:13,225 root  INFO     target_vocab_size: 39
2017-01-09 11:52:13,225 root  INFO     model_dir: train
2017-01-09 11:52:13,225 root  INFO     target_embedding_size: 10
2017-01-09 11:52:13,226 root  INFO     attn_num_hidden: 128
2017-01-09 11:52:13,226 root  INFO     attn_num_layers: 2
2017-01-09 11:52:13,226 root  INFO     buckets
2017-01-09 11:52:13,226 root  INFO     [(16, 11), (27, 17), (35, 19), (64, 22), (80, 32)]
Traceback (most recent call last):
  File "src/launcher.py", line 142, in <module>
    main(sys.argv[1:], exp_config.ExpConfig)
  File "src/launcher.py", line 138, in main
    old_model_version = parameters.old_model_version)
  File "/Users/logiz/www/test/Attention-OCR/src/model/model.py", line 119, in __init__
    cnn_model = CNN(self.img_data)
  File "/Users/logiz/www/test/Attention-OCR/src/model/cnn.py", line 30, in __init__
    self._build_network(input_tensor)
  File "/Users/logiz/www/test/Attention-OCR/src/model/cnn.py", line 43, in _build_network
    input_layer.set_input(input_tensor=input_tensor)
AttributeError: 'InputLayer' object has no attribute 'set_input'

how to fix,thank you.

**Comment by da03** [comment]
Can you report your Keras version?

**Comment by webluoye** [comment]
Keras (1.2.0)
tensorflow (0.12.1)

**Comment by da03** [comment]
Oh they are updating again... It is annoying that the interfaces are changing, my implementation was based on Keras 1.1.1. My suggestion is to downgrade Keras, since I might need some time to figure out what's the new interface.

**Comment by webluoye** [comment]
well,  thank you and wait your upgrade

**Comment by chaxor** [comment]
I had this problem as well!

The solution was to run the following:

`pip2 install keras==1.1.1`

**Comment by PrabakarSundar** [comment]
Downgrading tensorflow to 0.11.0 and keras to 1.1.1 worked for me
For Tensorflow:
1. $ export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.11.0-cp27-none-linux_x86_64.whl
2. $ sudo pip install --upgrade $TF_BINARY_URL

For Keras:
$ sudo pip install keras==1.1.1
