### ISSUE TITLE
model_with_buckets fails because of wildcard input size

### ISSUE THREAD

**Issue by joytafty** [da03/Attention-OCR#34]
Hi I'm trying to understand the run the training code, but I keep running into the issue on line 998 in `seq2seq.py`. As far as I can tell, it's because the encoder_inputs_tensor shape is (?, ?, 512) 

Here's the error: 
```Traceback (most recent call last):
  File "src/launcher.py", line 142, in <module>
    main(sys.argv[1:], exp_config.ExpConfig)
  File "src/launcher.py", line 138, in main
    old_model_version = parameters.old_model_version)
  File "/Users/trimchala/receipt-classification/Attention-OCR/src/model/model.py", line 143, in __init__
    use_gru = use_gru)
  File "/Users/trimchala/receipt-classification/Attention-OCR/src/model/seq2seq_model.py", line 145, in __init__
    softmax_loss_function=softmax_loss_function)
  File "/Users/trimchala/receipt-classification/Attention-OCR/src/model/seq2seq.py", line 998, in model_with_buckets
    encoder_inputs = tf.split(0, bucket[0], encoder_inputs_tensor)
  File "/Users/trimchala/miniconda/envs/tfenvPy35/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 1221, in split
    num = size_splits_shape.dims[0]
IndexError: list index out of range
```

I did change line 74 to `linear = tf.contrib.layers.linear`. I wonder if it affects anything. Could you help me figure out what the problem might be? Thanks a lot!

**Comment by HidayatRahman** [comment]
Try to Change the Vocabulary size and train it again on Characters. The Vocabulary size can be found in the exp_config file. TARGET_VOCAB_SIZE
