### ISSUE TITLE
During the execution of "Test and visualize attention results" i am getting error:

### ISSUE THREAD

**Issue by arsalan993** [da03/Attention-OCR#65]
I ran this command 
"python src/launcher.py --phase=test --visualize --data-path=evaluation_data/svt/test.txt --data-base-dir=evaluation_data/svt --log-path=log.txt --load-model --model-dir=model --output-dir=results"

my tensorflow version is 1.4 on both version of python
and i get this error
`Traceback (most recent call last):
  File "src/launcher.py", line 11, in <module>
    from model.model import Model
  File "/home/test/Desktop/Attention-OCR/src/model/model.py", line 17, in <module>
    from .seq2seq_model import Seq2SeqModel
  File "/home/test/Desktop/Attention-OCR/src/model/seq2seq_model.py", line 33, in <module>
    from .seq2seq import model_with_buckets
  File "/home/test/Desktop/Attention-OCR/src/model/seq2seq.py", line 73, in <module>
    linear = rnn_cell._linear # pylint: disable=protected-access
AttributeError: 'module' object has no attribute '_linear'`

**Comment by rahul1906** [comment]
I got the same error. Change tensorflow to some other previous version and run it again.

**Comment by mvrozanti** [comment]
Install `tensorflow==1.0` (#42)

**Comment by famunir** [comment]
Or instead of changing the version, this issue is solved by [#71](https://github.com/da03/Attention-OCR/issues/71)

**Comment by kspook** [comment]
in my case, i set environment as follows;
- python 3.5
- tensorflow==1.0
- cudatoolkit==9.0  (conda install -c anaconda cudatoolkit==9.0)
