### ISSUE TITLE
I switched to tensorflow 0.12.1 and Keras 1.1.1 but now i am getting this error

### ISSUE THREAD

**Issue by arsalan993** [da03/Attention-OCR#66]
CNN outdim before squeeze: (?, 1, ?, 512)
CNN outdim: (?, ?, 512)
Traceback (most recent call last):
  File "src/launcher.py", line 146, in <module>
    main(sys.argv[1:], exp_config.ExpConfig)
  File "src/launcher.py", line 142, in main
    session = sess)
  File "/home/test/Desktop/Attention-OCR/src/model/model.py", line 135, in __init__
    self.concat_conv_output = tf.concat(axis=1, values=[self.conv_output, self.zero_paddings])
TypeError: concat() got an unexpected keyword argument 'axis'

**Comment by alfredolozano** [comment]
I have the same issue, did you manage to solve it?

**Comment by arsalan993** [comment]
NOO

**Comment by alfredolozano** [comment]
I tried on an environment with Tensorflow 1.2 and keras 2.0 and this specific error got fixed.

**Comment by SJHBXShub** [comment]
hello, did you change the original code when you run on the environment with Tensorflow 1.2 and Keras 2.0  @alfredolozano

**Comment by alfredolozano** [comment]
I don't think so, what is your error message?

**Comment by XuXuanhui** [comment]
> self.concat_conv_output = tf.concat(axis=1, values=[self.conv_output, self.zero_paddings])

instead with self.concat_conv_output = tf.concat(1, [self.conv_output, self.zero_paddings])
