### ISSUE TITLE
Does it support special ascii characters ?

### ISSUE THREAD

**Issue by hskzlj** [da03/Attention-OCR#82]
Traceback (most recent call last):
--
File "src/launcher.py", line 146, in <module>
main(sys.argv[1:], exp_config.ExpConfig)
File "src/launcher.py", line 143, in main
model.launch()
File "/test/data/dl/ocr/Attention-OCR/src/model/model.py", line 224, in launch
for batch in self.s_gen.gen(self.batch_size):
File "/test/data/dl/ocr/Attention-OCR/src/data_util/data_gen.py", line 71, in gen
img_bw, word = self.read_data(img_path, lex)
File "/test/data/dl/ocr/Attention-OCR/src/data_util/data_gen.py", line 122, in read_data
assert 96 < ord(c) < 123 or 47 < ord(c) < 58
AssertionError

Can it be modified to ignore it?

**Comment by rahuladream** [comment]
Hey did you find the solution?

**Comment by vadimen** [comment]
you should find what id your special symbol has in unicode table, then you can do something like:  "assert 96 < ord(c) < 123 or 47 < ord(c) < 58 or ord(c) == you_symbol_id"
